# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file ''
#
# Created: Thu Aug 06 09:19:05 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mapView(object):
    def setupUi(self, mapView):
        mapView.setObjectName(_fromUtf8("mapView"))
        mapView.resize(730, 546)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/resources/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mapView.setWindowIcon(icon)
        mapView.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.gridLayout = QtGui.QGridLayout(mapView)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(mapView)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_4 = QtGui.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 710, 526))
        self.scrollAreaWidgetContents_4.setObjectName(_fromUtf8("scrollAreaWidgetContents_4"))
        self.tabs = QtGui.QTabWidget(self.scrollAreaWidgetContents_4)
        self.tabs.setGeometry(QtCore.QRect(0, 0, 721, 531))
        self.tabs.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabs.setUsesScrollButtons(False)
        self.tabs.setDocumentMode(False)
        self.tabs.setTabsClosable(False)
        self.tabs.setMovable(False)
        self.tabs.setObjectName(_fromUtf8("tabs"))
        self.projectTab = QtGui.QWidget()
        self.projectTab.setObjectName(_fromUtf8("projectTab"))
        self.label = QtGui.QLabel(self.projectTab)
        self.label.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.projectTab)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 71, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.projectName = QtGui.QLineEdit(self.projectTab)
        self.projectName.setGeometry(QtCore.QRect(90, 20, 591, 20))
        self.projectName.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.projectName.setObjectName(_fromUtf8("projectName"))
        self.projectDetails = QtGui.QPlainTextEdit(self.projectTab)
        self.projectDetails.setGeometry(QtCore.QRect(90, 50, 591, 231))
        self.projectDetails.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.projectDetails.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.projectDetails.setObjectName(_fromUtf8("projectDetails"))
        self.applybutton1 = QtGui.QPushButton(self.projectTab)
        self.applybutton1.setGeometry(QtCore.QRect(520, 460, 75, 23))
        self.applybutton1.setObjectName(_fromUtf8("applybutton1"))
        self.cancelbutton1 = QtGui.QPushButton(self.projectTab)
        self.cancelbutton1.setGeometry(QtCore.QRect(610, 460, 75, 23))
        self.cancelbutton1.setObjectName(_fromUtf8("cancelbutton1"))
        self.PAGE = QtGui.QLineEdit(self.projectTab)
        self.PAGE.setGeometry(QtCore.QRect(550, 400, 51, 20))
        self.PAGE.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.PAGE.setObjectName(_fromUtf8("PAGE"))
        self.ETYEAR = QtGui.QLineEdit(self.projectTab)
        self.ETYEAR.setGeometry(QtCore.QRect(530, 350, 41, 21))
        self.ETYEAR.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.ETYEAR.setInputMask(_fromUtf8(""))
        self.ETYEAR.setMaxLength(4)
        self.ETYEAR.setObjectName(_fromUtf8("ETYEAR"))
        self.ETTIME = QtGui.QLineEdit(self.projectTab)
        self.ETTIME.setGeometry(QtCore.QRect(660, 350, 41, 21))
        self.ETTIME.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.ETTIME.setInputMask(_fromUtf8(""))
        self.ETTIME.setObjectName(_fromUtf8("ETTIME"))
        self.STDAY = QtGui.QLineEdit(self.projectTab)
        self.STDAY.setGeometry(QtCore.QRect(620, 320, 31, 21))
        self.STDAY.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.STDAY.setInputMask(_fromUtf8(""))
        self.STDAY.setMaxLength(2)
        self.STDAY.setObjectName(_fromUtf8("STDAY"))
        self.ETMONTH = QtGui.QLineEdit(self.projectTab)
        self.ETMONTH.setGeometry(QtCore.QRect(580, 350, 31, 21))
        self.ETMONTH.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.ETMONTH.setInputMask(_fromUtf8(""))
        self.ETMONTH.setMaxLength(2)
        self.ETMONTH.setObjectName(_fromUtf8("ETMONTH"))
        self.PRTINT = QtGui.QLineEdit(self.projectTab)
        self.PRTINT.setGeometry(QtCore.QRect(550, 430, 51, 20))
        self.PRTINT.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.PRTINT.setObjectName(_fromUtf8("PRTINT"))
        self.label_9 = QtGui.QLabel(self.projectTab)
        self.label_9.setGeometry(QtCore.QRect(420, 320, 111, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_25 = QtGui.QLabel(self.projectTab)
        self.label_25.setGeometry(QtCore.QRect(440, 430, 111, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_38 = QtGui.QLabel(self.projectTab)
        self.label_38.setGeometry(QtCore.QRect(420, 290, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_15 = QtGui.QLabel(self.projectTab)
        self.label_15.setGeometry(QtCore.QRect(560, 380, 71, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_14 = QtGui.QLabel(self.projectTab)
        self.label_14.setGeometry(QtCore.QRect(420, 400, 131, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_26 = QtGui.QLabel(self.projectTab)
        self.label_26.setGeometry(QtCore.QRect(620, 430, 81, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.STYEAR = QtGui.QLineEdit(self.projectTab)
        self.STYEAR.setGeometry(QtCore.QRect(530, 320, 41, 21))
        self.STYEAR.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.STYEAR.setInputMask(_fromUtf8(""))
        self.STYEAR.setMaxLength(4)
        self.STYEAR.setObjectName(_fromUtf8("STYEAR"))
        self.label_10 = QtGui.QLabel(self.projectTab)
        self.label_10.setGeometry(QtCore.QRect(420, 350, 111, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.ETDAY = QtGui.QLineEdit(self.projectTab)
        self.ETDAY.setGeometry(QtCore.QRect(620, 350, 31, 21))
        self.ETDAY.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.ETDAY.setInputMask(_fromUtf8(""))
        self.ETDAY.setMaxLength(2)
        self.ETDAY.setObjectName(_fromUtf8("ETDAY"))
        self.STMONTH = QtGui.QLineEdit(self.projectTab)
        self.STMONTH.setGeometry(QtCore.QRect(580, 320, 31, 21))
        self.STMONTH.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.STMONTH.setInputMask(_fromUtf8(""))
        self.STMONTH.setMaxLength(2)
        self.STMONTH.setObjectName(_fromUtf8("STMONTH"))
        self.STTIME = QtGui.QLineEdit(self.projectTab)
        self.STTIME.setGeometry(QtCore.QRect(660, 320, 41, 21))
        self.STTIME.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.STTIME.setInputMask(_fromUtf8(""))
        self.STTIME.setObjectName(_fromUtf8("STTIME"))
        self.label_34 = QtGui.QLabel(self.projectTab)
        self.label_34.setGeometry(QtCore.QRect(230, 370, 81, 16))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.NBRA = QtGui.QLineEdit(self.projectTab)
        self.NBRA.setGeometry(QtCore.QRect(120, 290, 51, 21))
        self.NBRA.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.NBRA.setObjectName(_fromUtf8("NBRA"))
        self.label_6 = QtGui.QLabel(self.projectTab)
        self.label_6.setGeometry(QtCore.QRect(10, 380, 91, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_11 = QtGui.QLabel(self.projectTab)
        self.label_11.setGeometry(QtCore.QRect(250, 290, 51, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.DIFFUSno = QtGui.QRadioButton(self.projectTab)
        self.DIFFUSno.setGeometry(QtCore.QRect(170, 380, 41, 17))
        self.DIFFUSno.setChecked(False)
        self.DIFFUSno.setObjectName(_fromUtf8("DIFFUSno"))
        self.tribareasgroup = QtGui.QButtonGroup(mapView)
        self.tribareasgroup.setObjectName(_fromUtf8("tribareasgroup"))
        self.tribareasgroup.addButton(self.DIFFUSno)
        self.TAUFAC = QtGui.QLineEdit(self.projectTab)
        self.TAUFAC.setGeometry(QtCore.QRect(310, 370, 51, 21))
        self.TAUFAC.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.TAUFAC.setObjectName(_fromUtf8("TAUFAC"))
        self.WINDyes = QtGui.QRadioButton(self.projectTab)
        self.WINDyes.setGeometry(QtCore.QRect(120, 410, 41, 17))
        self.WINDyes.setChecked(False)
        self.WINDyes.setObjectName(_fromUtf8("WINDyes"))
        self.windsimgroup = QtGui.QButtonGroup(mapView)
        self.windsimgroup.setObjectName(_fromUtf8("windsimgroup"))
        self.windsimgroup.addButton(self.WINDyes)
        self.SOPERno = QtGui.QRadioButton(self.projectTab)
        self.SOPERno.setGeometry(QtCore.QRect(170, 350, 41, 17))
        self.SOPERno.setChecked(False)
        self.SOPERno.setObjectName(_fromUtf8("SOPERno"))
        self.controlstructuregroup = QtGui.QButtonGroup(mapView)
        self.controlstructuregroup.setObjectName(_fromUtf8("controlstructuregroup"))
        self.controlstructuregroup.addButton(self.SOPERno)
        self.label_3 = QtGui.QLabel(self.projectTab)
        self.label_3.setGeometry(QtCore.QRect(10, 290, 111, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.GRAVenglish = QtGui.QRadioButton(self.projectTab)
        self.GRAVenglish.setGeometry(QtCore.QRect(290, 290, 61, 17))
        self.GRAVenglish.setChecked(False)
        self.GRAVenglish.setObjectName(_fromUtf8("GRAVenglish"))
        self.unitgroup = QtGui.QButtonGroup(mapView)
        self.unitgroup.setObjectName(_fromUtf8("unitgroup"))
        self.unitgroup.addButton(self.GRAVenglish)
        self.SFAC = QtGui.QLineEdit(self.projectTab)
        self.SFAC.setGeometry(QtCore.QRect(310, 340, 51, 21))
        self.SFAC.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.SFAC.setObjectName(_fromUtf8("SFAC"))
        self.label_33 = QtGui.QLabel(self.projectTab)
        self.label_33.setGeometry(QtCore.QRect(230, 320, 141, 16))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.SOPERyes = QtGui.QRadioButton(self.projectTab)
        self.SOPERyes.setGeometry(QtCore.QRect(120, 350, 41, 17))
        self.SOPERyes.setChecked(True)
        self.SOPERyes.setObjectName(_fromUtf8("SOPERyes"))
        self.controlstructuregroup.addButton(self.SOPERyes)
        self.WINDno = QtGui.QRadioButton(self.projectTab)
        self.WINDno.setGeometry(QtCore.QRect(170, 410, 41, 17))
        self.WINDno.setChecked(False)
        self.WINDno.setObjectName(_fromUtf8("WINDno"))
        self.windsimgroup.addButton(self.WINDno)
        self.label_7 = QtGui.QLabel(self.projectTab)
        self.label_7.setGeometry(QtCore.QRect(10, 410, 91, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.ZL = QtGui.QLineEdit(self.projectTab)
        self.ZL.setGeometry(QtCore.QRect(120, 440, 51, 21))
        self.ZL.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.ZL.setObjectName(_fromUtf8("ZL"))
        self.GRAVmetric = QtGui.QRadioButton(self.projectTab)
        self.GRAVmetric.setGeometry(QtCore.QRect(360, 290, 51, 17))
        self.GRAVmetric.setChecked(False)
        self.GRAVmetric.setObjectName(_fromUtf8("GRAVmetric"))
        self.unitgroup.addButton(self.GRAVmetric)
        self.label_4 = QtGui.QLabel(self.projectTab)
        self.label_4.setGeometry(QtCore.QRect(10, 320, 111, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.projectTab)
        self.label_5.setGeometry(QtCore.QRect(10, 350, 101, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_8 = QtGui.QLabel(self.projectTab)
        self.label_8.setGeometry(QtCore.QRect(10, 440, 111, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.DIFFUSyes = QtGui.QRadioButton(self.projectTab)
        self.DIFFUSyes.setGeometry(QtCore.QRect(120, 380, 41, 17))
        self.DIFFUSyes.setChecked(False)
        self.DIFFUSyes.setObjectName(_fromUtf8("DIFFUSyes"))
        self.tribareasgroup.addButton(self.DIFFUSyes)
        self.label_32 = QtGui.QLabel(self.projectTab)
        self.label_32.setGeometry(QtCore.QRect(230, 340, 71, 16))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.NEX = QtGui.QLineEdit(self.projectTab)
        self.NEX.setGeometry(QtCore.QRect(120, 320, 51, 21))
        self.NEX.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.NEX.setObjectName(_fromUtf8("NEX"))
        self.tabs.addTab(self.projectTab, _fromUtf8(""))
        self.computationsTab = QtGui.QWidget()
        self.computationsTab.setObjectName(_fromUtf8("computationsTab"))
        self.EPSFAC_3 = QtGui.QLineEdit(self.computationsTab)
        self.EPSFAC_3.setGeometry(QtCore.QRect(310, 810, 51, 20))
        self.EPSFAC_3.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.EPSFAC_3.setObjectName(_fromUtf8("EPSFAC_3"))
        self.MKNT_3 = QtGui.QLineEdit(self.computationsTab)
        self.MKNT_3.setGeometry(QtCore.QRect(310, 840, 51, 20))
        self.MKNT_3.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.MKNT_3.setObjectName(_fromUtf8("MKNT_3"))
        self.label_77 = QtGui.QLabel(self.computationsTab)
        self.label_77.setGeometry(QtCore.QRect(370, 840, 361, 16))
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.QSMALL_3 = QtGui.QLineEdit(self.computationsTab)
        self.QSMALL_3.setGeometry(QtCore.QRect(610, 910, 51, 20))
        self.QSMALL_3.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.QSMALL_3.setObjectName(_fromUtf8("QSMALL_3"))
        self.label_78 = QtGui.QLabel(self.computationsTab)
        self.label_78.setGeometry(QtCore.QRect(670, 910, 361, 16))
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.NUMGT_3 = QtGui.QLineEdit(self.computationsTab)
        self.NUMGT_3.setGeometry(QtCore.QRect(310, 870, 51, 20))
        self.NUMGT_3.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.NUMGT_3.setObjectName(_fromUtf8("NUMGT_3"))
        self.label_79 = QtGui.QLabel(self.computationsTab)
        self.label_79.setGeometry(QtCore.QRect(370, 870, 431, 16))
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.label_80 = QtGui.QLabel(self.computationsTab)
        self.label_80.setGeometry(QtCore.QRect(260, 840, 51, 16))
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.label_81 = QtGui.QLabel(self.computationsTab)
        self.label_81.setGeometry(QtCore.QRect(370, 810, 361, 16))
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.label_82 = QtGui.QLabel(self.computationsTab)
        self.label_82.setGeometry(QtCore.QRect(260, 870, 51, 16))
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.label_83 = QtGui.QLabel(self.computationsTab)
        self.label_83.setGeometry(QtCore.QRect(260, 910, 291, 16))
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.line_9 = QtGui.QFrame(self.computationsTab)
        self.line_9.setGeometry(QtCore.QRect(260, 890, 531, 16))
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.textBrowser_3 = QtGui.QTextBrowser(self.computationsTab)
        self.textBrowser_3.setGeometry(QtCore.QRect(260, 950, 256, 181))
        self.textBrowser_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser_3.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_3.setObjectName(_fromUtf8("textBrowser_3"))
        self.label_84 = QtGui.QLabel(self.computationsTab)
        self.label_84.setGeometry(QtCore.QRect(550, 910, 51, 16))
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.STDCW_3 = QtGui.QRadioButton(self.computationsTab)
        self.STDCW_3.setGeometry(QtCore.QRect(460, 930, 61, 17))
        self.STDCW_3.setObjectName(_fromUtf8("STDCW_3"))
        self.line_10 = QtGui.QFrame(self.computationsTab)
        self.line_10.setGeometry(QtCore.QRect(530, 910, 20, 211))
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.STDCX_3 = QtGui.QRadioButton(self.computationsTab)
        self.STDCX_3.setGeometry(QtCore.QRect(390, 930, 61, 17))
        self.STDCX_3.setObjectName(_fromUtf8("STDCX_3"))
        self.STDW_3 = QtGui.QRadioButton(self.computationsTab)
        self.STDW_3.setGeometry(QtCore.QRect(320, 930, 61, 17))
        self.STDW_3.setObjectName(_fromUtf8("STDW_3"))
        self.STDX_3 = QtGui.QRadioButton(self.computationsTab)
        self.STDX_3.setGeometry(QtCore.QRect(260, 930, 51, 17))
        self.STDX_3.setObjectName(_fromUtf8("STDX_3"))
        self.MAXIT_3 = QtGui.QLineEdit(self.computationsTab)
        self.MAXIT_3.setGeometry(QtCore.QRect(270, 620, 51, 20))
        self.MAXIT_3.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.MAXIT_3.setObjectName(_fromUtf8("MAXIT_3"))
        self.MKNT_4 = QtGui.QLineEdit(self.computationsTab)
        self.MKNT_4.setGeometry(QtCore.QRect(270, 740, 51, 20))
        self.MKNT_4.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.MKNT_4.setObjectName(_fromUtf8("MKNT_4"))
        self.line_11 = QtGui.QFrame(self.computationsTab)
        self.line_11.setGeometry(QtCore.QRect(220, 640, 391, 16))
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.EPSB_3 = QtGui.QLineEdit(self.computationsTab)
        self.EPSB_3.setGeometry(QtCore.QRect(270, 590, 51, 20))
        self.EPSB_3.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.EPSB_3.setObjectName(_fromUtf8("EPSB_3"))
        self.label_85 = QtGui.QLabel(self.computationsTab)
        self.label_85.setGeometry(QtCore.QRect(330, 740, 361, 16))
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.EPSSYS_3 = QtGui.QLineEdit(self.computationsTab)
        self.EPSSYS_3.setGeometry(QtCore.QRect(270, 680, 51, 20))
        self.EPSSYS_3.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.EPSSYS_3.setObjectName(_fromUtf8("EPSSYS_3"))
        self.QSMALL_4 = QtGui.QLineEdit(self.computationsTab)
        self.QSMALL_4.setGeometry(QtCore.QRect(570, 810, 51, 20))
        self.QSMALL_4.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.QSMALL_4.setObjectName(_fromUtf8("QSMALL_4"))
        self.label_86 = QtGui.QLabel(self.computationsTab)
        self.label_86.setGeometry(QtCore.QRect(330, 590, 361, 16))
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.label_87 = QtGui.QLabel(self.computationsTab)
        self.label_87.setGeometry(QtCore.QRect(630, 810, 361, 16))
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.label_88 = QtGui.QLabel(self.computationsTab)
        self.label_88.setGeometry(QtCore.QRect(330, 680, 361, 16))
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.NUMGT_4 = QtGui.QLineEdit(self.computationsTab)
        self.NUMGT_4.setGeometry(QtCore.QRect(270, 770, 51, 20))
        self.NUMGT_4.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.NUMGT_4.setObjectName(_fromUtf8("NUMGT_4"))
        self.label_89 = QtGui.QLabel(self.computationsTab)
        self.label_89.setGeometry(QtCore.QRect(330, 770, 431, 16))
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.label_90 = QtGui.QLabel(self.computationsTab)
        self.label_90.setGeometry(QtCore.QRect(220, 740, 51, 16))
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.EPSFAC_4 = QtGui.QLineEdit(self.computationsTab)
        self.EPSFAC_4.setGeometry(QtCore.QRect(270, 710, 51, 20))
        self.EPSFAC_4.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.EPSFAC_4.setObjectName(_fromUtf8("EPSFAC_4"))
        self.label_91 = QtGui.QLabel(self.computationsTab)
        self.label_91.setGeometry(QtCore.QRect(220, 680, 51, 16))
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.label_92 = QtGui.QLabel(self.computationsTab)
        self.label_92.setGeometry(QtCore.QRect(330, 620, 361, 16))
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.label_93 = QtGui.QLabel(self.computationsTab)
        self.label_93.setGeometry(QtCore.QRect(330, 710, 361, 16))
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.label_94 = QtGui.QLabel(self.computationsTab)
        self.label_94.setGeometry(QtCore.QRect(220, 770, 51, 16))
        self.label_94.setObjectName(_fromUtf8("label_94"))
        self.label_95 = QtGui.QLabel(self.computationsTab)
        self.label_95.setGeometry(QtCore.QRect(220, 590, 46, 13))
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.label_96 = QtGui.QLabel(self.computationsTab)
        self.label_96.setGeometry(QtCore.QRect(220, 710, 51, 16))
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.label_97 = QtGui.QLabel(self.computationsTab)
        self.label_97.setGeometry(QtCore.QRect(220, 810, 291, 16))
        self.label_97.setObjectName(_fromUtf8("label_97"))
        self.label_98 = QtGui.QLabel(self.computationsTab)
        self.label_98.setGeometry(QtCore.QRect(220, 660, 231, 16))
        self.label_98.setObjectName(_fromUtf8("label_98"))
        self.line_12 = QtGui.QFrame(self.computationsTab)
        self.line_12.setGeometry(QtCore.QRect(220, 790, 531, 16))
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.textBrowser_4 = QtGui.QTextBrowser(self.computationsTab)
        self.textBrowser_4.setGeometry(QtCore.QRect(220, 850, 256, 181))
        self.textBrowser_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser_4.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_4.setObjectName(_fromUtf8("textBrowser_4"))
        self.label_99 = QtGui.QLabel(self.computationsTab)
        self.label_99.setGeometry(QtCore.QRect(510, 810, 51, 16))
        self.label_99.setObjectName(_fromUtf8("label_99"))
        self.STDCW_4 = QtGui.QRadioButton(self.computationsTab)
        self.STDCW_4.setGeometry(QtCore.QRect(420, 830, 61, 17))
        self.STDCW_4.setObjectName(_fromUtf8("STDCW_4"))
        self.line_13 = QtGui.QFrame(self.computationsTab)
        self.line_13.setGeometry(QtCore.QRect(490, 810, 20, 211))
        self.line_13.setFrameShape(QtGui.QFrame.VLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.STDCX_4 = QtGui.QRadioButton(self.computationsTab)
        self.STDCX_4.setGeometry(QtCore.QRect(350, 830, 61, 17))
        self.STDCX_4.setObjectName(_fromUtf8("STDCX_4"))
        self.STDW_4 = QtGui.QRadioButton(self.computationsTab)
        self.STDW_4.setGeometry(QtCore.QRect(280, 830, 61, 17))
        self.STDW_4.setObjectName(_fromUtf8("STDW_4"))
        self.STDX_4 = QtGui.QRadioButton(self.computationsTab)
        self.STDX_4.setGeometry(QtCore.QRect(470, 1450, 51, 17))
        self.STDX_4.setObjectName(_fromUtf8("STDX_4"))
        self.STDX_5 = QtGui.QRadioButton(self.computationsTab)
        self.STDX_5.setGeometry(QtCore.QRect(220, 830, 51, 17))
        self.STDX_5.setObjectName(_fromUtf8("STDX_5"))
        self.MKNT = QtGui.QLineEdit(self.computationsTab)
        self.MKNT.setGeometry(QtCore.QRect(60, 210, 51, 20))
        self.MKNT.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.MKNT.setObjectName(_fromUtf8("MKNT"))
        self.line_2 = QtGui.QFrame(self.computationsTab)
        self.line_2.setGeometry(QtCore.QRect(10, 110, 391, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_35 = QtGui.QLabel(self.computationsTab)
        self.label_35.setGeometry(QtCore.QRect(10, 40, 231, 16))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_30 = QtGui.QLabel(self.computationsTab)
        self.label_30.setGeometry(QtCore.QRect(10, 90, 46, 13))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.EPSB = QtGui.QLineEdit(self.computationsTab)
        self.EPSB.setGeometry(QtCore.QRect(60, 60, 51, 20))
        self.EPSB.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.EPSB.setObjectName(_fromUtf8("EPSB"))
        self.line_3 = QtGui.QFrame(self.computationsTab)
        self.line_3.setGeometry(QtCore.QRect(10, 20, 391, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label_22 = QtGui.QLabel(self.computationsTab)
        self.label_22.setGeometry(QtCore.QRect(120, 210, 361, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.QSMALL = QtGui.QLineEdit(self.computationsTab)
        self.QSMALL.setGeometry(QtCore.QRect(360, 280, 51, 20))
        self.QSMALL.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.QSMALL.setObjectName(_fromUtf8("QSMALL"))
        self.EPSSYS = QtGui.QLineEdit(self.computationsTab)
        self.EPSSYS.setGeometry(QtCore.QRect(60, 150, 51, 20))
        self.EPSSYS.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.EPSSYS.setObjectName(_fromUtf8("EPSSYS"))
        self.label_29 = QtGui.QLabel(self.computationsTab)
        self.label_29.setGeometry(QtCore.QRect(120, 60, 361, 16))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_37 = QtGui.QLabel(self.computationsTab)
        self.label_37.setGeometry(QtCore.QRect(420, 280, 361, 16))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_18 = QtGui.QLabel(self.computationsTab)
        self.label_18.setGeometry(QtCore.QRect(120, 150, 361, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.NUMGT = QtGui.QLineEdit(self.computationsTab)
        self.NUMGT.setGeometry(QtCore.QRect(60, 240, 51, 20))
        self.NUMGT.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.NUMGT.setObjectName(_fromUtf8("NUMGT"))
        self.label_24 = QtGui.QLabel(self.computationsTab)
        self.label_24.setGeometry(QtCore.QRect(120, 240, 431, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_21 = QtGui.QLabel(self.computationsTab)
        self.label_21.setGeometry(QtCore.QRect(10, 210, 51, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.EPSFAC = QtGui.QLineEdit(self.computationsTab)
        self.EPSFAC.setGeometry(QtCore.QRect(60, 180, 51, 20))
        self.EPSFAC.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.EPSFAC.setObjectName(_fromUtf8("EPSFAC"))
        self.label_20 = QtGui.QLabel(self.computationsTab)
        self.label_20.setGeometry(QtCore.QRect(120, 180, 361, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_17 = QtGui.QLabel(self.computationsTab)
        self.label_17.setGeometry(QtCore.QRect(10, 150, 51, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_31 = QtGui.QLabel(self.computationsTab)
        self.label_31.setGeometry(QtCore.QRect(120, 90, 361, 16))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.SSEPS = QtGui.QLineEdit(self.computationsTab)
        self.SSEPS.setGeometry(QtCore.QRect(60, 0, 51, 20))
        self.SSEPS.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.SSEPS.setObjectName(_fromUtf8("SSEPS"))
        self.label_23 = QtGui.QLabel(self.computationsTab)
        self.label_23.setGeometry(QtCore.QRect(10, 240, 51, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_28 = QtGui.QLabel(self.computationsTab)
        self.label_28.setGeometry(QtCore.QRect(10, 60, 46, 13))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_19 = QtGui.QLabel(self.computationsTab)
        self.label_19.setGeometry(QtCore.QRect(10, 180, 51, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_27 = QtGui.QLabel(self.computationsTab)
        self.label_27.setGeometry(QtCore.QRect(10, 280, 291, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_16 = QtGui.QLabel(self.computationsTab)
        self.label_16.setGeometry(QtCore.QRect(10, 130, 231, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.line = QtGui.QFrame(self.computationsTab)
        self.line.setGeometry(QtCore.QRect(10, 260, 531, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.textBrowser = QtGui.QTextBrowser(self.computationsTab)
        self.textBrowser.setGeometry(QtCore.QRect(10, 320, 256, 181))
        self.textBrowser.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.label_36 = QtGui.QLabel(self.computationsTab)
        self.label_36.setGeometry(QtCore.QRect(300, 280, 51, 16))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.STDCW = QtGui.QRadioButton(self.computationsTab)
        self.STDCW.setGeometry(QtCore.QRect(210, 300, 61, 17))
        self.STDCW.setObjectName(_fromUtf8("STDCW"))
        self.goveqgroup = QtGui.QButtonGroup(mapView)
        self.goveqgroup.setObjectName(_fromUtf8("goveqgroup"))
        self.goveqgroup.addButton(self.STDCW)
        self.line_4 = QtGui.QFrame(self.computationsTab)
        self.line_4.setGeometry(QtCore.QRect(280, 280, 20, 211))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.label_12 = QtGui.QLabel(self.computationsTab)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 46, 13))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.STDCX = QtGui.QRadioButton(self.computationsTab)
        self.STDCX.setGeometry(QtCore.QRect(140, 300, 61, 17))
        self.STDCX.setObjectName(_fromUtf8("STDCX"))
        self.goveqgroup.addButton(self.STDCX)
        self.STDW = QtGui.QRadioButton(self.computationsTab)
        self.STDW.setGeometry(QtCore.QRect(70, 300, 61, 17))
        self.STDW.setObjectName(_fromUtf8("STDW"))
        self.goveqgroup.addButton(self.STDW)
        self.label_13 = QtGui.QLabel(self.computationsTab)
        self.label_13.setGeometry(QtCore.QRect(120, 0, 311, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.STDX = QtGui.QRadioButton(self.computationsTab)
        self.STDX.setGeometry(QtCore.QRect(10, 300, 51, 17))
        self.STDX.setObjectName(_fromUtf8("STDX"))
        self.goveqgroup.addButton(self.STDX)
        self.MAXIT = QtGui.QLineEdit(self.computationsTab)
        self.MAXIT.setGeometry(QtCore.QRect(60, 90, 51, 20))
        self.MAXIT.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.MAXIT.setObjectName(_fromUtf8("MAXIT"))
        self.applybutton2 = QtGui.QPushButton(self.computationsTab)
        self.applybutton2.setGeometry(QtCore.QRect(520, 460, 75, 23))
        self.applybutton2.setObjectName(_fromUtf8("applybutton2"))
        self.cancelbutton2 = QtGui.QPushButton(self.computationsTab)
        self.cancelbutton2.setGeometry(QtCore.QRect(610, 460, 75, 23))
        self.cancelbutton2.setObjectName(_fromUtf8("cancelbutton2"))
        self.tabs.addTab(self.computationsTab, _fromUtf8(""))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(mapView)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mapView)

    def retranslateUi(self, mapView):
        mapView.setWindowTitle(_translate("mapView", "FEQinput - Map View", None))
        self.label.setText(_translate("mapView", "Project Name", None))
        self.label_2.setText(_translate("mapView", "Project Details", None))
        self.applybutton1.setText(_translate("mapView", "Apply", None))
        self.cancelbutton1.setText(_translate("mapView", "Cancel", None))
        self.ETYEAR.setText(_translate("mapView", "YYYY", None))
        self.ETTIME.setText(_translate("mapView", "TIME", None))
        self.STDAY.setText(_translate("mapView", "DD", None))
        self.ETMONTH.setText(_translate("mapView", "MM", None))
        self.label_9.setText(_translate("mapView", "Simulation Start Time:", None))
        self.label_25.setText(_translate("mapView", "Print output at every", None))
        self.label_38.setText(_translate("mapView", "Simulation:", None))
        self.label_15.setText(_translate("mapView", "<html><head/><body><p><span style=\" font-weight:600;\">OUTPUT FILE</span></p></body></html>", None))
        self.label_14.setText(_translate("mapView", "Number of lines per page:", None))
        self.label_26.setText(_translate("mapView", "steps", None))
        self.STYEAR.setText(_translate("mapView", "YYYY", None))
        self.label_10.setText(_translate("mapView", "Simulation End Time:", None))
        self.ETDAY.setText(_translate("mapView", "DD", None))
        self.STMONTH.setText(_translate("mapView", "MM", None))
        self.STTIME.setText(_translate("mapView", "TIME", None))
        self.label_34.setText(_translate("mapView", "Tributary areas:", None))
        self.label_6.setText(_translate("mapView", "Tributary Areas:", None))
        self.label_11.setText(_translate("mapView", "<html><head/><body><p><span style=\" font-weight:600;\">Units:</span></p></body></html>", None))
        self.DIFFUSno.setText(_translate("mapView", "No", None))
        self.WINDyes.setText(_translate("mapView", "Yes", None))
        self.SOPERno.setText(_translate("mapView", "No", None))
        self.label_3.setText(_translate("mapView", "Number of branches:", None))
        self.GRAVenglish.setText(_translate("mapView", "English", None))
        self.label_33.setText(_translate("mapView", "Unit conversion factors:", None))
        self.SOPERyes.setText(_translate("mapView", "Yes", None))
        self.WINDno.setText(_translate("mapView", "No", None))
        self.label_7.setText(_translate("mapView", "Wind Simulation:", None))
        self.GRAVmetric.setText(_translate("mapView", "Metric", None))
        self.label_4.setText(_translate("mapView", "Number of end nodes:", None))
        self.label_5.setText(_translate("mapView", "Control structures?", None))
        self.label_8.setText(_translate("mapView", "Zero inertia depth:", None))
        self.DIFFUSyes.setText(_translate("mapView", "Yes", None))
        self.label_32.setText(_translate("mapView", "Node stations:", None))
        self.tabs.setTabText(self.tabs.indexOf(self.projectTab), _translate("mapView", "Project", None))
        self.label_77.setText(_translate("mapView", "<html><head/><body><p><span style=\" font-style:italic;\">maximum number of iterations for the matrix system</span></p></body></html>", None))
        self.label_78.setText(_translate("mapView", "<html><head/><body><p><span style=\" font-style:italic;\">small flow (prevents division by 0)</span></p></body></html>", None))
        self.label_79.setText(_translate("mapView", "<html><head/><body><p><span style=\" font-style:italic;\">number of nodes at which the secondary relative convergence criterion may be applied</span></p></body></html>", None))
        self.label_80.setText(_translate("mapView", "MKNT=", None))
        self.label_81.setText(_translate("mapView", "<html><head/><body><p><span style=\" font-style:italic;\">secondary relative tolerance factor</span></p></body></html>", None))
        self.label_82.setText(_translate("mapView", "NUMGT=", None))
        self.label_83.setText(_translate("mapView", "Governing equation for branches in the stream system:", None))
        self.textBrowser_3.setHtml(_translate("mapView", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">STDX: </span><span style=\" font-size:8pt; font-style:italic;\">the weight coefficients for curvilinearity are assumed to always be equal to 1.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt; font-style:italic;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">STDW: </span><span style=\" font-size:8pt; font-style:italic;\">a special user-controlled variable weight for certain distance integrals is added to the STDX equations. Select this when simulating shallow flows.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">STDCX: </span><span style=\" font-size:8pt; font-style:italic;\">adds weights to account for channel curvilinearity to the STDX equations.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">STDCW: </span><span style=\" font-size:8pt; font-style:italic;\">adds weights to account for channel curvilinearity to the STDW equations.</span></p></body></html>", None))
        self.label_84.setText(_translate("mapView", "QSMALL=", None))
        self.STDCW_3.setText(_translate("mapView", "STDCW", None))
        self.STDCX_3.setText(_translate("mapView", "STDCX", None))
        self.STDW_3.setText(_translate("mapView", "STDW", None))
        self.STDX_3.setText(_translate("mapView", "STDX", None))
        self.label_85.setText(_translate("mapView", "<html><head/><body><p><span style=\" font-style:italic;\">maximum number of iterations for the matrix system</span></p></body></html>", None))
        self.label_86.setText(_translate("mapView", "<html><head/><body><p><span style=\" font-style:italic;\">convergence tolerance for initial conditions in steady-state flow analysis</span></p></body></html>", None))
        self.label_87.setText(_translate("mapView", "<html><head/><body><p><span style=\" font-style:italic;\">small flow (prevents division by 0)</span></p></body></html>", None))
        self.label_88.setText(_translate("mapView", "<html><head/><body><p><span style=\" font-style:italic;\">maximum relative change in the value of an unknown between iterations</span></p></body></html>", None))
        self.label_89.setText(_translate("mapView", "<html><head/><body><p><span style=\" font-style:italic;\">number of nodes at which the secondary relative convergence criterion may be applied</span></p></body></html>", None))
        self.label_90.setText(_translate("mapView", "MKNT=", None))
        self.label_91.setText(_translate("mapView", "EPSSYS=", None))
        self.label_92.setText(_translate("mapView", "<html><head/><body><p><span style=\" font-style:italic;\">maximum number of iterations in steady-state flow analysis</span></p></body></html>", None))
        self.label_93.setText(_translate("mapView", "<html><head/><body><p><span style=\" font-style:italic;\">secondary relative tolerance factor</span></p></body></html>", None))
        self.label_94.setText(_translate("mapView", "NUMGT=", None))
        self.label_95.setText(_translate("mapView", "EPSB=", None))
        self.label_96.setText(_translate("mapView", "EPSFAC=", None))
        self.label_97.setText(_translate("mapView", "Governing equation for branches in the stream system:", None))
        self.label_98.setText(_translate("mapView", "Convergence tolerances for the Matrix solution", None))
        self.textBrowser_4.setHtml(_translate("mapView", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">STDX: </span><span style=\" font-size:8pt; font-style:italic;\">the weight coefficients for curvilinearity are assumed to always be equal to 1.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt; font-style:italic;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">STDW: </span><span style=\" font-size:8pt; font-style:italic;\">a special user-controlled variable weight for certain distance integrals is added to the STDX equations. Select this when simulating shallow flows.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">STDCX: </span><span style=\" font-size:8pt; font-style:italic;\">adds weights to account for channel curvilinearity to the STDX equations.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">STDCW: </span><span style=\" font-size:8pt; font-style:italic;\">adds weights to account for channel curvilinearity to the STDW equations.</span></p></body></html>", None))
        self.label_99.setText(_translate("mapView", "QSMALL=", None))
        self.STDCW_4.setText(_translate("mapView", "STDCW", None))
        self.STDCX_4.setText(_translate("mapView", "STDCX", None))
        self.STDW_4.setText(_translate("mapView", "STDW", None))
        self.STDX_4.setText(_translate("mapView", "STDX", None))
        self.STDX_5.setText(_translate("mapView", "STDX", None))
        self.label_35.setText(_translate("mapView", "Steady State Flow", None))
        self.label_30.setText(_translate("mapView", "MAXIT=", None))
        self.label_22.setText(_translate("mapView", "<html><head/><body><p><span style=\" font-style:italic;\">maximum number of iterations for the matrix system</span></p></body></html>", None))
        self.label_29.setText(_translate("mapView", "<html><head/><body><p><span style=\" font-style:italic;\">convergence tolerance for initial conditions in steady-state flow analysis</span></p></body></html>", None))
        self.label_37.setText(_translate("mapView", "<html><head/><body><p><span style=\" font-style:italic;\">small flow (prevents division by 0)</span></p></body></html>", None))
        self.label_18.setText(_translate("mapView", "<html><head/><body><p><span style=\" font-style:italic;\">maximum relative change in the value of an unknown between iterations</span></p></body></html>", None))
        self.label_24.setText(_translate("mapView", "<html><head/><body><p><span style=\" font-style:italic;\">number of nodes at which the secondary relative convergence criterion may be applied</span></p></body></html>", None))
        self.label_21.setText(_translate("mapView", "MKNT=", None))
        self.label_20.setText(_translate("mapView", "<html><head/><body><p><span style=\" font-style:italic;\">secondary relative tolerance factor</span></p></body></html>", None))
        self.label_17.setText(_translate("mapView", "EPSSYS=", None))
        self.label_31.setText(_translate("mapView", "<html><head/><body><p><span style=\" font-style:italic;\">maximum number of iterations in steady-state flow analysis</span></p></body></html>", None))
        self.label_23.setText(_translate("mapView", "NUMGT=", None))
        self.label_28.setText(_translate("mapView", "EPSB=", None))
        self.label_19.setText(_translate("mapView", "EPSFAC=", None))
        self.label_27.setText(_translate("mapView", "Governing equation for branches in the stream system:", None))
        self.label_16.setText(_translate("mapView", "Convergence tolerances for the Matrix solution", None))
        self.textBrowser.setHtml(_translate("mapView", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">STDX: </span><span style=\" font-size:8pt; font-style:italic;\">the weight coefficients for curvilinearity are assumed to always be equal to 1.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt; font-style:italic;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">STDW: </span><span style=\" font-size:8pt; font-style:italic;\">a special user-controlled variable weight for certain distance integrals is added to the STDX equations. Select this when simulating shallow flows.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">STDCX: </span><span style=\" font-size:8pt; font-style:italic;\">adds weights to account for channel curvilinearity to the STDX equations.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">STDCW: </span><span style=\" font-size:8pt; font-style:italic;\">adds weights to account for channel curvilinearity to the STDW equations.</span></p></body></html>", None))
        self.label_36.setText(_translate("mapView", "QSMALL=", None))
        self.STDCW.setText(_translate("mapView", "STDCW", None))
        self.label_12.setText(_translate("mapView", "SSEPS=", None))
        self.STDCX.setText(_translate("mapView", "STDCX", None))
        self.STDW.setText(_translate("mapView", "STDW", None))
        self.label_13.setText(_translate("mapView", "<html><head/><body><p><span style=\" font-style:italic;\">maximum relative change in surcharge storage volume allowed</span></p></body></html>", None))
        self.STDX.setText(_translate("mapView", "STDX", None))
        self.applybutton2.setText(_translate("mapView", "Apply", None))
        self.cancelbutton2.setText(_translate("mapView", "Cancel", None))
        self.tabs.setTabText(self.tabs.indexOf(self.computationsTab), _translate("mapView", "Computations", None))

import resources_rc
